crm_site:
    resource: "@CRMSiteBundle/Resources/config/routing.yml"
    prefix:   /

crm_support:
    resource: "@CRMSupportBundle/Resources/config/routing.yml"
    prefix:   /

crm_sale:
    resource: "@CRMSaleBundle/Resources/config/routing.yml"
    prefix:   /

crm_user:
    resource: "@CRMUserBundle/Resources/config/routing.yml"
    prefix:   /

crm_contact:
    resource: "@CRMContactBundle/Resources/config/routing.yml"
    prefix:   /
my_user_management:
    resource: "@CRMUserBundle/Resources/config/routing.yml"
    
#HWIOAuthBundle routes
hwi_oauth_security:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix: /login
 
hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix: /login
 
hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /login
 
facebook_login:
    pattern: /login/check-facebook
 
google_login:
    pattern: /login/check-google