parameters:
#    crm_support.example.class: CRM\SupportBundle\Example

services:
#    crm_support.example:
#        class: %crm_support.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
